--
--Mohammednaeem Meman
--

DROP DATABASE IF EXISTS assn456;
CREATE DATABASE assn456;

\connect assn456

BEGIN;

DROP TABLE IF EXISTS securities CASCADE;
DROP TABLE IF EXISTS fundamentals;
DROP TABLE IF EXISTS prices;

--SECURITIES

CREATE TABLE securities(
	"SYMBOL" CHAR(5) PRIMARY KEY,
	"COMPANY" TEXT,
	"SECTOR" TEXT,
	"SUB-INDUSTRY" TEXT,
	"INITIAL TRADE DATE" DATE
);

\COPY securities FROM './securities.csv' DELIMITER ',' CSV;

--FUNDAMENTALS
	
CREATE TABLE fundamentals(
	"ID" INTEGER PRIMARY KEY,
	"SYMBOL" CHAR(5) REFERENCES securities("SYMBOL"),
	"YEAR ENDING" DATE,
	"CASH AND CASH EQUIVALENTS" NUMERIC(15,2),
	"EARNINGS BEFORE INTEREST AND TAXES" NUMERIC(15,2),
	"GROSS MARGIN" INTEGER,
	"NET INCOME" NUMERIC(15,2),
	"TOTAL ASSETS" NUMERIC(15,2),
	"TOTAL LIABILITIES" NUMERIC(15,2),
	"TOTAL REVENUE" NUMERIC(15,2),
	"YEAR" DOUBLE PRECISION,
	"EARNINGS PER SHARE" NUMERIC(15,2),
	"SHARES OUTSTANDING" NUMERIC(15,4)
);

\COPY fundamentals FROM './fundamentals.csv' DELIMITER ',' CSV;

--PRICES

CREATE TABLE prices(
	"DATE" DATE,
	"SYMBOL" CHAR(5),
	"OPEN" NUMERIC(15,6),
	"CLOSE" NUMERIC(15,6),
	"LOW" NUMERIC(15,6),
	"HIGH" NUMERIC(15,6),
	"VOLUME" INTEGER,
	CONSTRAINT prices_fkey FOREIGN KEY ("SYMBOL") REFERENCES securities("SYMBOL"),
	CONSTRAINT prices_pkey PRIMARY KEY ("DATE", "SYMBOL")
);

\COPY prices FROM './prices.csv' DELIMITER ',' CSV;

COMMIT;